version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50

  user_service:
    build: 
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - microservices_network
    volumes:
      - ./user_service:/app

  order_service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - microservices_network
    volumes:
      - ./order_service:/app

networks:
  microservices_network:
    driver: bridge

volumes:
  redis_data: 