apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapp-deployment
  labels:
    app: fastapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapp
  template:
    metadata:
      labels:
        app: fastapp
    spec:
      containers:
      - name: fastapp
        image: solverbot/fastapp:0.05
        env:
        - name: APP_ENV
          value: "production"
        ports:
        - containerPort: 8086
        resources:
          requests:
            cpu: 1
            memory: 512Mi 
          limits:
            memory: 700Mi
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 15
