version: '3.8'

services:
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: 1234 
  #     POSTGRES_DB: appdb
  #     # POSTGRES_HOST_AUTH_METHOD: md5
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data
  #     # - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
  #     # - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U user"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

# volumes:
  # postgres_data:

